type Status = {
  status: number;
  application: {
    ach_key: string | null;
    ach_status: number;
    amount: number;
    approved_by: string;
    bank_account_id: string;
    bank_account_number: null;
    bank_account_type: null;
    bank_address: null;
    bank_name: string;
    country: string;
    current_employee: string;
    current_employee_address: string;
    customer_id: string;
    date_applied: string;
    date_approved: string;
    date_of_birth: string;
    email: string;
    employment_status: string;
    gender: string;
    id: number;
    income: number;
    job_title: string;
    kenyan_address: string;
    loan_id: string;
    mandate_id: string;
    marital_status: string;
    next_of_kin_address: string;
    next_of_kin_fullname: string;
    next_of_kin_phone_number: string;
    next_of_kin_relationship: string;
    passport_number: string;
    phone_no: string;
    place_of_birth: string;
    rejection_reason: null | string;
    remark: string;
    rent: number;
    residential_status: string;
    routing_number: null | string;
    social_security_number: string;
    status: number;
    sub_status: number;
    subscription_id: string;
    title: string;
    usa_address: string;
    visa_doc: null | string;
  };
  loan: {
    approved_by: string;
    completed_email_sent: number;
    contract_sign_date: string | null;
    country: string | null;
    date_approved: string;
    email: string;
    fullnames: string;
    id: number;
    intake: string;
    interest: number;
    ip_address: number | null;
    issue_date: string;
    loan_contract: string | null;
    loan_id: string;
    loan_type: string;
    location: string | null;
    maturity_date: string;
    member_no: string;
    origination_fee: number;
    phone: string;
    principal: number;
    remark: string;
    status: number;
    student_accept: number | null;
    term: number;
    total_loan: number;
    total_payable: number;
    to_pay: number | undefined;
  };
};
export type { Status };
