import axios from "axios";

const counties = [
  { value: 1, label: "Mombasa" },
  { value: 2, label: "Kwale" },
  { value: 3, label: "Kilifi" },
  { value: 4, label: "Tana River" },
  { value: 5, label: "Lamu" },
  { value: 6, label: "Taita Taveta" },
  { value: 7, label: "Garissa" },
  { value: 8, label: "Wajir" },
  { value: 9, label: "Mandera" },
  { value: 10, label: "Marsabit" },
  { value: 11, label: "Isiolo" },
  { value: 12, label: "Meru" },
  { value: 13, label: "Tharaka Nithi" },
  { value: 14, label: "Embu" },
  { value: 15, label: "Kitui" },
  { value: 16, label: "Machakos" },
  { value: 17, label: "Makueni" },
  { value: 18, label: "Nyandarua" },
  { value: 19, label: "Nyeri" },
  { value: 20, label: "Kirinyaga" },
  { value: 21, label: "Murang'a" },
  { value: 22, label: "Kiambu" },
  { value: 23, label: "Turkana" },
  { value: 24, label: "West Pokot" },
  { value: 25, label: "Samburu" },
  { value: 26, label: "Trans Nzoia" },
  { value: 27, label: "Uasin Gishu" },
  { value: 28, label: "Elgeyo Marakwet" },
  { value: 29, label: "Nandi" },
  { value: 30, label: "Baringo" },
  { value: 31, label: "Laikipia" },
  { value: 32, label: "Nakuru" },
  { value: 33, label: "Narok" },
  { value: 34, label: "Kajiado" },
  { value: 35, label: "Kericho" },
  { value: 36, label: "Bomet" },
  { value: 37, label: "Kakamega" },
  { value: 38, label: "Vihiga" },
  { value: 39, label: "Bungoma" },
  { value: 40, label: "Busia" },
  { value: 41, label: "Siaya" },
  { value: 42, label: "Kisumu" },
  { value: 43, label: "Homa Bay" },
  { value: 44, label: "Migori" },
  { value: 45, label: "Kisii" },
  { value: 46, label: "Nyamira" },
  { value: 47, label: "Nairobi" },
];
const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (fmr. 'Swaziland')",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia (formerly Macedonia)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City (Holy See)",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const fundingOptions = [
  { value: "statement", label: "Bank Statement" },
  { value: "loan", label: "Student Loan" },
  { value: "scholarship", label: "Scholarship or GA" },
];
const acceptReject = [
  { value: "accept", label: "Accept" },
  { value: "reject", label: "Reject" },
];
const yesNoOptions = [
  { value: "yes", label: "Yes" },
  { value: "no", label: "No" },
];

export { counties, countries, fundingOptions, acceptReject, yesNoOptions };
